# Generated by Django 3.1 on 2020-09-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exerciseplans_product_type'),
        ('merchandise', '0002_product_product_type'),
        ('nutrition', '0003_nutritionplans_product_type'),
        ('checkout', '0002_auto_20200919_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_cart',
        ),
        migrations.AlterField(
            model_name='exerciselineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_lineitems', to='exercise.exerciseplans'),
        ),
        migrations.AlterField(
            model_name='nutritionlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_lineitems', to='nutrition.nutritionplans'),
        ),
        migrations.AlterField(
            model_name='productlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lineitems', to='merchandise.product'),
        ),
    ]
