# Generated by Django 3.1 on 2020-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200928_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exercise_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='nutrition_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
