# Generated by Django 3.1 on 2020-09-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200928_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exercise_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nutrition_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_total',
        ),
    ]
