# Generated by Django 3.1 on 2020-09-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_product_product_type'),
        ('exercise', '0003_exerciseplans_product_type'),
        ('nutrition', '0003_nutritionplans_product_type'),
        ('checkout', '0005_auto_20200928_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciseplans'),
        ),
        migrations.AlterField(
            model_name='nutritionlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutritionplans'),
        ),
        migrations.AlterField(
            model_name='productlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.product'),
        ),
    ]
