# Generated by Django 3.1 on 2020-10-26 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='your_review',
            field=models.TextField(default=django.utils.timezone.now, max_length=1500),
            preserve_default=False,
        ),
    ]
