# Generated by Django 3.1 on 2020-08-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionplans',
            options={'verbose_name_plural': 'Nutrition Plans'},
        ),
    ]
