# Generated by Django 3.1 on 2020-09-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20200822_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplans',
            name='product_type',
            field=models.CharField(default='nutrition_plan', max_length=254),
        ),
    ]
