# Generated by Django 3.1 on 2020-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_nutritionplans_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
