# Generated by Django 3.1 on 2020-10-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_nutritionplans_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplans',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
