# Generated by Django 3.1 on 2020-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('timing', models.CharField(max_length=120)),
                ('access', models.CharField(max_length=254)),
                ('free_offer', models.CharField(max_length=500)),
                ('accompanied_guest', models.CharField(max_length=220)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
