# Generated by Django 3.1 on 2020-08-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseplans',
            options={'verbose_name_plural': 'Exercise Plans'},
        ),
    ]
