# Generated by Django 3.1 on 2020-10-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exerciseplans_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
