# Generated by Django 3.1 on 2020-10-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exerciseplans_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplans',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
