# Generated by Django 3.1 on 2020-09-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='merchandise', max_length=254),
        ),
    ]
